#!/usr/bin/python

import argparse
import traceback

import core.hived_logger as hived_logger
from audispd_listener import AudispdListener
from config import GeneralConfig
from core.modules import import_event_handlers


def start_daemon():
    hived_logger.info("Hived has been started", "Hived")
    listener = AudispdListener()
    handlers = import_event_handlers()
    for h in handlers:
        listener.add_observer(h)
    listener.listen()


def handle_command(arguments: argparse.Namespace):
    if arguments.start:
        try:
            start_daemon()
        except Exception as _:
            hived_logger.error_traceback(
                f"something went wrong: {traceback.format_exc()} --- End of Traceback ---"
            )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Hived")
    parser.set_defaults(func=handle_command)
    group = parser.add_mutually_exclusive_group(required=False)
    group.add_argument(
        "-v",
        "--version",
        help="View currently installed version.",
        action="version",
        version=f"v{GeneralConfig.VERSION}",
    )
    group.add_argument(
        "-s", "--start", help="Start the hived daemon", action="store_true"
    )

    args = parser.parse_args()
    args.func(args)
